CREATE DATABASE biometric_system;
USE biometric_system;

-- -----------------------------------------------------
-- TIPO DOCUMENTO
-- -----------------------------------------------------
CREATE TABLE tipo_documento
 (
  ID_TIPO_DOC VARCHAR(10)  NOT NULL  ,
  DES_TD VARCHAR(30) NOT NULL ,
  ESTADO_TD TINYINT(1) NOT NULL ,
  PRIMARY KEY (ID_TIPO_DOC)
  );
  
  
 -- -----------------------------------------------------
-- PERSONA
-- -----------------------------------------------------
CREATE TABLE persona
 (
  ID_PERSONA VARCHAR(15) NOT NULL,
  TD_PERSONA VARCHAR(10) NOT NULL,
  PRIMER_NOMBRE VARCHAR(45) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR(45) NULL,
  PRIMER_APELLIDO VARCHAR(45) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR(45) NULL,
  TELEFONO BIGINT(15) NOT NULL ,
  PRIMARY KEY (ID_PERSONA, TD_PERSONA)
);

 -- -----------------------------------------------------
-- ROL
-- -----------------------------------------------------
CREATE TABLE rol
 (
  ID_ROL INT NOT NULL ,
  DESC_ROL VARCHAR(45) NOT NULL ,
  ESTADO_ROL BOOLEAN  NOT NULL ,
  PRIMARY KEY (ID_ROL)
  );
  
  CREATE TABLE parentesco
 (
  ID_PARENTESCO INT NOT NULL,
  DES_PARENTESCO VARCHAR(45) NOT NULL ,
  ESTADO_PARENTESCO TINYINT(1) NOT NULL ,
  PRIMARY KEY (ID_PARENTESCO)
  );
  
  CREATE TABLE beneficiario
 (
  ID_BENEFICIARIO VARCHAR(15) NOT NULL ,
  TD_BENEFICIARIO VARCHAR(10) NOT NULL,
  ESTADO_BENEFICIARIO BOOLEAN NOT NULL,
  PRIMARY KEY (ID_BENEFICIARIO, TD_BENEFICIARIO)
  );
  -- -----------------------------------------------------
-- RECUPERAR CONTRASEÑA
-- -----------------------------------------------------
CREATE TABLE recuperar
 (
  ID_RECUPERACION INT NOT NULL AUTO_INCREMENT ,
  CORREO_RECUP VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_RECUPERACION)
  );

 -- -----------------------------------------------------
-- CAMBIO_CONTRASEÑA
-- -----------------------------------------------------
CREATE TABLE cambio_contraseña
 (
  ID_CAMBIO INT NOT NULL AUTO_INCREMENT,
  CONTRA_ANTERIOR VARCHAR(45) NOT NULL,
  CONTRA_NUEVA VARCHAR(45) NOT NULL,
  CONFIRAMCION_CONTRA VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_CAMBIO)
  );
  
CREATE TABLE usuario
(
  ID_USUARIO INT NOT NULL,
  NUMERO_DOC VARCHAR(15) NOT NULL,
  TD_USUARIO VARCHAR(10) NOT NULL,
  CONTRASEÑA VARCHAR(12) NOT NULL,
  CORREO_USUARIO VARCHAR(45) NOT NULL,
  ESTADO_USUARIO BOOLEAN NOT NULL,
  RECUPERAR_CONTRASEÑA INT,
  CAMBIO_CONTRASEÑA INT,
  PRIMARY KEY (ID_USUARIO, NUMERO_DOC, TD_USUARIO)
  );
  
  CREATE TABLE contacto_emergencia
 (
  ID_CONTACTO VARCHAR(15) NOT NUll ,
  TD_CONTACTO VARCHAR(10) NOT NULL ,
  ESTADO_CONTACTO BOOLEAN NOT NULL,
  ID_PARENTESCO_C INT NOT NULL,
  PRIMARY KEY (ID_CONTACTO, TD_CONTACTO)
  );
  
   -- -----------------------------------------------------
-- ROL_USUARIO
-- -----------------------------------------------------
CREATE TABLE rol_usuario
 (
  ROL_ID_ROL INT NOT NULL,
  USUARIO_ID_USUARIO INT NOT NULL,
  USUARIO_NUMERO_DOC VARCHAR(15) NOT NULL,
  USUARIO_TD_USUARIO VARCHAR(10) NOT NULL,
  PRIMARY KEY (ROL_ID_ROL, USUARIO_ID_USUARIO, USUARIO_NUMERO_DOC, USUARIO_TD_USUARIO)
  );
  
  -- -----------------------------------------------------
-- LOGIN
-- -----------------------------------------------------
CREATE TABLE login
 (
  ID_LOGIN INT NOT NULL ,
  NUMERO_DOC_LOG VARCHAR(15) NOT NULL ,
  TIPO_DOC VARCHAR(10) NOT NULL,
  CONTRASEÑA_LOGIN VARCHAR(45) NOT NULL,
  ROL_ID_ROL INT NOT NULL,
  PRIMARY KEY (ID_LOGIN, NUMERO_DOC_LOG, TIPO_DOC)
   );
   -- -----------------------------------------------------
-- CIUDAD
-- -----------------------------------------------------
CREATE TABLE ciudad
(
  ID_CIUDAD INT NOT NULL AUTO_INCREMENT ,
  DES_CIUDAD VARCHAR(45) NOT NULL ,
  ESTADO_CIUDAD BOOLEAN NOT NULL ,
  PRIMARY KEY (ID_CIUDAD)
  );
  
  -- -----------------------------------------------------
-- EPS
-- -----------------------------------------------------
CREATE TABLE eps
(
  ID_EPS INT NOT NULL AUTO_INCREMENT ,
  DES_EPS VARCHAR(20) NOT NULL ,
  ESTADO_EPS BOOLEAN NOT NULL ,
  PRIMARY KEY (ID_EPS)
  );
  
-- -----------------------------------------------------
-- CLIENTE
-- -----------------------------------------------------
CREATE TABLE cliente
 (
  ID_CLIENTE VARCHAR(15) NOT NULL ,
  TD_CLIENTE VARCHAR(10) NOT NULL ,
  DIRECCION VARCHAR(45) NOT NULL ,
  ESTADO_CLIENTE TINYINT(1) NOT NULL ,
  NUMERO_DOC_CONTACTO_E VARCHAR(15) NOT NULL ,
  TD_CONTACTO_E VARCHAR(10) NOT NULL,
  FK_CIUDAD INT NOT NULL  ,
  FK_EPS INT NOT NULL,
  PRIMARY KEY (ID_CLIENTE, TD_CLIENTE)
  );
  
   -- -----------------------------------------------------
-- ADMINISTRADOR
-- -----------------------------------------------------
CREATE TABLE administrador
 (
  USUARIO_NUMERO_DOC VARCHAR(15) NOT NULL ,
  USUARIO_TD_USUARIO VARCHAR(10) NOT NULL ,
  PRIMARY KEY (USUARIO_NUMERO_DOC, USUARIO_TD_USUARIO)
 );
 
  -- -----------------------------------------------------
-- TIPO_VEHICULO
-- -----------------------------------------------------
CREATE TABLE tipo_vehiculo
(
  ID_TIPO_VEH INT NOT NULL ,
  DESC_TV VARCHAR(15) NOT NULL,
  ESTADO_TV BOOLEAN NOT NULL ,
  PRIMARY KEY (ID_TIPO_VEH)
);

-- -----------------------------------------------------
-- MODELO_VEHICULO
-- -----------------------------------------------------
CREATE TABLE modelo_vehiculo
 (
  ID_MODELO INT NOT NULL ,
  DES_MODELO VARCHAR(45) NOT NULL ,
  ESTADO_MODELO BOOLEAN NOT NULL ,
  PRIMARY KEY (ID_MODELO)
 );
 
  -- -----------------------------------------------------
-- BIOMETRICO
-- -----------------------------------------------------
CREATE TABLE biometrico
 (
  ID_BIOMETRICO VARCHAR(20) NOT NULL ,
  PRIMARY KEY (ID_BIOMETRICO)
 );
 
 
 -- -----------------------------------------------------
-- VEHICULO
-- -----------------------------------------------------
CREATE TABLE vehiculo
 (
  PLACA VARCHAR(15) NOT NULL ,
  COLOR VARCHAR(20) NOT NULL ,
  ESTADO_VEHI TINYINT(1) NOT NULL ,
  FK_TIPO_VEHICULO INT NOT NULL ,
  FK_MODELO INT NOT NULL ,
  FK_BIOMETRICO VARCHAR(20) NOT NULL ,
  PRIMARY KEY (PLACA)
);

 -- -----------------------------------------------------
-- CLIENTE_VEHICULO
-- -----------------------------------------------------
CREATE TABLE cliente_vehiculo
 (
  ID_CLIENTE_VEH VARCHAR(15) NOT NULL,
  TD_CLIENTE_VEH VARCHAR(10) NOT NULL ,
  VEHICULO_PLACA VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID_CLIENTE_VEH, TD_CLIENTE_VEH, VEHICULO_PLACA)
  );
  
  
 -- -----------------------------------------------------
-- BENEFICIARIO_CLIENTE
-- -----------------------------------------------------
CREATE TABLE beneficiario_cliente
 (
  BENEFICIARIO_ID_BENEFICIARIO VARCHAR(15) NOT NULL,
  BENEFICIARIO_TD_BENEFICIARIO VARCHAR(10) NOT NULL,
  CLIENTE_ID_CLIENTE VARCHAR(15) NOT NULL,
  CLIENTE_TD_CLIENTE VARCHAR(10) NOT NULL,
  FK_PARENTESCO INT  NOT NULL,
  PRIMARY KEY (BENEFICIARIO_ID_BENEFICIARIO, BENEFICIARIO_TD_BENEFICIARIO, CLIENTE_ID_CLIENTE, CLIENTE_TD_CLIENTE)
);

  
  -- -----------------------------------------------------
-- HUELLA
-- -----------------------------------------------------
CREATE TABLE huella
(
  ID_HUELLA INT NOT NULL AUTO_INCREMENT ,
  DESC_HUELLA VARCHAR(45) NOT NULL ,
  HORA DATETIME NOT NULL ,
  FECHA DATETIME NOT NULL ,
  ESTADO_HUELLA BOOLEAN NULL ,
  FK_BIOMETRICO VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_HUELLA)
  );

-- -----------------------------------------------------
-- INGRESO_BENEFICIARIO
-- -----------------------------------------------------
CREATE TABLE ingreso_beneficiario
 (
  ID_INGRESO_BENEF INT NOT NULL ,
  BENEFICIARIO_ID_BENEFICIARIO VARCHAR(15) NOT NULL ,
  BENEFICIARIO_TD_BENEFICIARIO VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID_INGRESO_BENEF)
 );
 
  -- -----------------------------------------------------
-- INGRESO_CLIENTE
-- -----------------------------------------------------
CREATE TABLE ingreso_cliente
 (
  ID_INGRESO_CLIENTE INT NOT NULL,
  CLIENTE_ID_CLIENTE VARCHAR(15) NOT NULL,
  CLIENTE_TD_CLIENTE VARCHAR(10) NOT NULL,
  PRIMARY KEY (ID_INGRESO_CLIENTE)
  );
  
   -- -----------------------------------------------------
-- HISTORIAL_ENCENDIDO
-- -----------------------------------------------------
CREATE TABLE historial
(
  ID_HISTORIAL INT AUTO_INCREMENT NOT NULL, 
  FECHA_HISTORIAL DATETIME NOT NULL,
  HORA_HISTORIAL DATETIME NOT NULL,
  FK_CLIENTE_H VARCHAR(15) NOT NULL,
  FK_TD_CLIENTE_H VARCHAR(10) NOT NULL,
  FK_BENEFICIARIO_H VARCHAR(15) NOT NULL,
  FK_TD_BENEFICIARIO_H VARCHAR(10) NOT NULL,
  FK_VEHICULO_H VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID_HISTORIAL)
  );
  
     -- -----------------------------------------------------
-- PERFIL
-- -----------------------------------------------------
   CREATE TABLE perfil
(
  ID_PERFIL INT AUTO_INCREMENT NOT NULL, 
  ID_CLIENTE_P VARCHAR(15)NOT NULL,
  TD_CLIENTE_P VARCHAR(10)NOT NULL,
  FK_BENEFICIARIO_P VARCHAR(15) NOT NULL,
  FK_TD_BENEFICIARIO_P VARCHAR(10) NOT NULL,
  FK_VEHICULO_P VARCHAR(15) NOT NULL,
  PRIMARY KEY(ID_PERFIL)
  );
  
  -- ------------------------------------------------------
  -- LLAVES FORANEAS --------------------------------------
  
 -- LLAVES FORANEAS PERSONA
  ALTER TABLE persona
  ADD CONSTRAINT fk_PERSONA_TIPO_DOCUMENTO
  FOREIGN KEY (TD_PERSONA)
  REFERENCES tipo_documento (ID_TIPO_DOC)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

-- LLAVES FORANEAS BENEFICIARIO
    ALTER TABLE beneficiario
    ADD CONSTRAINT fk_CLIENTE_PERSONA1
    FOREIGN KEY (ID_BENEFICIARIO, TD_BENEFICIARIO)
    REFERENCES persona (ID_PERSONA , TD_PERSONA)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- LLAVES FORANEAS USUARIO
    ALTER TABLE usuario
    ADD CONSTRAINT fk_USUARIO_PERSONA1
    FOREIGN KEY (NUMERO_DOC , TD_USUARIO)
    REFERENCES persona (ID_PERSONA ,TD_PERSONA)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_USUARIO_RECUPERACION1
    FOREIGN KEY (RECUPERAR_CONTRASEÑA)
    REFERENCES recuperar (ID_RECUPERACION)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
	ADD CONSTRAINT fk_USUARIO_CAMBIO_CONTRASEÑA1
    FOREIGN KEY (CAMBIO_CONTRASEÑA)
    REFERENCES cambio_contraseña (ID_CAMBIO)
	ON DELETE CASCADE
    ON UPDATE CASCADE;

  -- LLAVES FORANEAS COTACTO_EMERGENCIA   
    ALTER TABLE contacto_emergencia
    ADD CONSTRAINT fk_ACUDIENTE_PERSONA1
    FOREIGN KEY (ID_CONTACTO , TD_CONTACTO)
    REFERENCES persona(ID_PERSONA, TD_PERSONA),
    ADD CONSTRAINT fk_PARENTESCO
    FOREIGN KEY (ID_PARENTESCO_C)
    REFERENCES parentesco(ID_PARENTESCO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

 -- LLAVES FORANEAS ROL_USUARIO
    ALTER TABLE  rol_usuario
    ADD CONSTRAINT fk_ROL_has_USUARIO_ROL1
    FOREIGN KEY (ROL_ID_ROL)
    REFERENCES rol(ID_ROL)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_ROL_has_USUARIO_USUARIO1
    FOREIGN KEY (USUARIO_ID_USUARIO, USUARIO_NUMERO_DOC , USUARIO_TD_USUARIO)
    REFERENCES usuario (ID_USUARIO, NUMERO_DOC , TD_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

    -- LLAVES FORANEAS LOGIN
    ALTER TABLE login
    ADD CONSTRAINT fk_LOGIN_USUARIO1
    FOREIGN KEY (NUMERO_DOC_LOG,TIPO_DOC)
    REFERENCES usuario(NUMERO_DOC, TD_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_LOGIN_ROL1
    FOREIGN KEY (ROL_ID_ROL)
    REFERENCES rol(ID_ROL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

    -- LLAVES FORANEAS CLIENTE
    ALTER TABLE cliente
    ADD CONSTRAINT fk_CLIENTE_USUARIO1
    FOREIGN KEY (ID_CLIENTE , TD_CLIENTE)
    REFERENCES usuario(NUMERO_DOC , TD_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_CLIENTE_ACUDIENTE1
    FOREIGN KEY (NUMERO_DOC_CONTACTO_E , TD_CONTACTO_E)
    REFERENCES contacto_emergencia(ID_CONTACTO, TD_CONTACTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_CLIENTE_CIUDAD1
    FOREIGN KEY (FK_CIUDAD)
    REFERENCES ciudad (ID_CIUDAD)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_CLIENTE_EPS1
    FOREIGN KEY (FK_EPS)
    REFERENCES eps(ID_EPS)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

  -- LLAVES FORANEAS VEHICULO
    ALTER TABLE vehiculo
    ADD CONSTRAINT fk_VEHICULO_TIPO_VEHICULO1
    FOREIGN KEY (FK_TIPO_VEHICULO)
    REFERENCES tipo_vehiculo (ID_TIPO_VEH)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_VEHICULO_MARCA_VEHICULO1
    FOREIGN KEY (FK_MODELO)
    REFERENCES modelo_vehiculo(ID_MODELO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_VEHICULO_BIOMETRICO1
    FOREIGN KEY (FK_BIOMETRICO)
    REFERENCES biometrico (ID_BIOMETRICO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
    
-- LLAVES FORANEAS CLIENTE_VEHICULO
    ALTER TABLE cliente_vehiculo
    ADD CONSTRAINT fk_CLIENTE_has_VEHICULO_CLIENTE1
    FOREIGN KEY (ID_CLIENTE_VEH , TD_CLIENTE_VEH)
    REFERENCES cliente(ID_CLIENTE,TD_CLIENTE)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_CLIENTE_has_VEHICULO_VEHICULO1
    FOREIGN KEY (VEHICULO_PLACA)
    REFERENCES vehiculo(PLACA)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
    
-- LLAVES FORANEAS BENEFICIARIO_CLIENTE
    ALTER TABLE beneficiario_cliente
    ADD CONSTRAINT fk_BENEFICIARIO_has_CLIENTE_BENEFICIARIO1
    FOREIGN KEY (BENEFICIARIO_ID_BENEFICIARIO, BENEFICIARIO_TD_BENEFICIARIO)
    REFERENCES biometric_system.BENEFICIARIO (ID_BENEFICIARIO, TD_BENEFICIARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
   ADD CONSTRAINT fk_BENEFICIARIO_has_CLIENTE_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_CLIENTE , CLIENTE_TD_CLIENTE)
    REFERENCES biometric_system.CLIENTE(ID_CLIENTE , TD_CLIENTE)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
   ADD CONSTRAINT fk_BENEFICIARIO_CLIENTE_PARENTESCO1
    FOREIGN KEY (FK_PARENTESCO)
    REFERENCES biometric_system.PARENTESCO(ID_PARENTESCO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- LLAVES FORANEAS HUELLA
    ALTER TABLE huella
    ADD CONSTRAINT fk_HUELLA_BIOMETRICO1
    FOREIGN KEY (FK_BIOMETRICO)
    REFERENCES biometrico (ID_BIOMETRICO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- LLAVES FORANEAS INGRESO_BENEFICIARIO
    ALTER TABLE ingreso_beneficiario
    ADD CONSTRAINT fk_INGRESO_BENEFICIARIO_BENEFICIARIO1
    FOREIGN KEY (BENEFICIARIO_ID_BENEFICIARIO , BENEFICIARIO_TD_BENEFICIARIO)
    REFERENCES biometric_system.BENEFICIARIO (ID_BENEFICIARIO , TD_BENEFICIARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_INGRESO_BENEFICIARIO_HUELLA1
    FOREIGN KEY (ID_INGRESO_BENEF)
    REFERENCES biometric_system.HUELLA (ID_HUELLA)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- LLAVES FORANEAS INGRESO_CLIENTE
    ALTER TABLE ingreso_cliente
    ADD CONSTRAINT fk_INGRESO_CLIENTE_CLIENTE1
    FOREIGN KEY (CLIENTE_ID_CLIENTE , CLIENTE_TD_CLIENTE)
    REFERENCES cliente(ID_CLIENTE , TD_CLIENTE)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    ADD CONSTRAINT fk_INGRESO_CLIENTE_HUELLA1
    FOREIGN KEY (ID_INGRESO_CLIENTE)
    REFERENCES huella(ID_HUELLA)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- LLAVES FORANEAS HISTORIAL
  ALTER TABLE historial
  ADD CONSTRAINT fk_HISTORIAL_CLIENTE
  FOREIGN KEY (FK_CLIENTE_H,FK_TD_CLIENTE_H)
  REFERENCES cliente(ID_CLIENTE,TD_CLIENTE)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  ADD CONSTRAINT FK_HISTORIAL_BENEFICIARIO
  FOREIGN KEY (FK_BENEFICIARIO_H, FK_TD_BENEFICIARIO_H)
  REFERENCES beneficiario(ID_BENEFICIARIO, TD_BENEFICIARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  ADD CONSTRAINT FK_HISTORIAL_VEHICULO
  FOREIGN KEY(FK_VEHICULO_H)
  REFERENCES vehiculo(PLACA)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

-- LLAVES FORANEAS PERFIL 
  ALTER TABLE perfil
  ADD CONSTRAINT FK_PERFIL_CLIENTE
  FOREIGN KEY (ID_CLIENTE_P,TD_CLIENTE_P)
  REFERENCES biometric_system.CLIENTE(ID_CLIENTE,TD_CLIENTE)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  ADD CONSTRAINT FK_PERFIL_BENEFICIARIO
  FOREIGN KEY (FK_BENEFICIARIO_P, FK_TD_BENEFICIARIO_P)
  REFERENCES biometric_system.BENEFICIARIO(ID_BENEFICIARIO, TD_BENEFICIARIO)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  ADD CONSTRAINT FK_PERFIL_VEHICULO
  FOREIGN KEY(FK_VEHICULO_P)
  REFERENCES biometric_system.VEHICULO(PLACA)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
  


